global:
  scrape_interval: 15s        # how often Prometheus pulls metrics
  evaluation_interval: 15s    # how often rules/alerts are evaluated
  scrape_timeout: 10s         # max time allowed per scrape

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
        
scrape_configs:
  - job_name: 'node_exporter' # infra
    static_configs:
      - targets:
          - 'node-exporter:9100'
        labels:
          env: production
          region: india
          team: devops
    relabel_configs:
      - target_label: instance
        replacement: 'server'

  - job_name: 'node'            # apps
    static_configs:
      - targets: ['node1:9100']

  - job_name: 'nginx'           # proxy
    static_configs:
      - targets: ['nginx:9113']

  - job_name: 'mysql'           # db
    static_configs:
      - targets: ['mysql-exporter:9104']

  - job_name: 'secure-app'      # Secure apps
    scheme: https
    basic_auth:
      username: admin
      password: password
    # tls_config:
    #   ca_file: /etc/prometheus/ca.pem
